[package]
name = "api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "genuflow"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
db = { path = "../db" }
anchor = { path = "../anchor" }
webhooks = { path = "../webhooks" }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
anyhow = "1"
argon2 = "0.5"
jsonwebtoken = "9"
qrcode = "0.14"
image = "0.25"
csv = "1"
hmac = "0.12"
subtle = "2"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
