#![deny(warnings)]

//! Queries against the `invites` table.

use chrono::{DateTime, Utc};
use common::{Invite, UserRole};
use tracing::instrument;
use uuid::Uuid;

use crate::Db;

/// Create a pending invite. The token is generated by Postgres
/// (`DEFAULT gen_random_uuid()`) so the caller never sees the raw
/// material until this returns.
#[instrument(skip(db), err)]
pub async fn create(
    db: &Db,
    brand_id: Uuid,
    email: &str,
    role: UserRole,
    expires_at: DateTime<Utc>,
) -> Result<Invite, sqlx::Error> {
    sqlx::query_as::<_, Invite>(
        r#"
        INSERT INTO invites (brand_id, email, role, expires_at)
        VALUES ($1, $2, $3, $4)
        RETURNING id, brand_id, email, role, token, expires_at, accepted_at, created_at
        "#,
    )
    .bind(brand_id)
    .bind(email)
    .bind(role)
    .bind(expires_at)
    .fetch_one(db)
    .await
}

/// Atomically claim an invite by its token. Executes a single
/// `UPDATE ... RETURNING` that sets `accepted_at = NOW()` only if the
/// row is unaccepted and not yet expired; if any of those conditions
/// fail, the result is empty and the caller surfaces a 400 without
/// being able to distinguish *why* it was not claimable (don't oracle
/// the reason — invalid / expired / used are all "not claimable").
///
/// This replaces the legacy read-then-check-then-mark sequence and
/// removes the race window where two concurrent submissions of the
/// same token could each pass the read-time `accepted_at IS NULL`
/// check.
///
/// `token` is skipped from the tracing span — it is secret material
/// for the duration of the invite's TTL and must not land in logs.
#[instrument(skip(db, token), err)]
pub async fn claim_by_token(db: &Db, token: Uuid) -> Result<Option<Invite>, sqlx::Error> {
    sqlx::query_as::<_, Invite>(
        r#"
        UPDATE invites
        SET accepted_at = NOW()
        WHERE token = $1
          AND accepted_at IS NULL
          AND expires_at > NOW()
        RETURNING id, brand_id, email, role, token, expires_at, accepted_at, created_at
        "#,
    )
    .bind(token)
    .fetch_optional(db)
    .await
}

/// Resolve an invite by its token without claiming it. Used by paths
/// that need to inspect (rather than consume) the invite. Returns
/// `None` if no row matches. The caller is responsible for checking
/// the row's `expires_at` and `accepted_at` fields.
///
/// `token` is skipped from the tracing span — it is secret material
/// for the duration of the invite's TTL.
#[instrument(skip(db, token), err)]
pub async fn get_by_token(db: &Db, token: Uuid) -> Result<Option<Invite>, sqlx::Error> {
    sqlx::query_as::<_, Invite>(
        r#"
        SELECT id, brand_id, email, role, token, expires_at, accepted_at, created_at
        FROM invites
        WHERE token = $1
        "#,
    )
    .bind(token)
    .fetch_optional(db)
    .await
}

/// List a brand's unaccepted invites, newest first.
#[instrument(skip(db), err)]
pub async fn list_pending_by_brand(
    db: &Db,
    brand_id: Uuid,
) -> Result<Vec<Invite>, sqlx::Error> {
    sqlx::query_as::<_, Invite>(
        r#"
        SELECT id, brand_id, email, role, token, expires_at, accepted_at, created_at
        FROM invites
        WHERE brand_id = $1
          AND accepted_at IS NULL
        ORDER BY created_at DESC
        "#,
    )
    .bind(brand_id)
    .fetch_all(db)
    .await
}

/// Mark an invite accepted at `at`. Idempotent in the sense that calling
/// twice with the same row only succeeds once — the WHERE clause filters
/// already-accepted rows out.
#[instrument(skip(db), err)]
pub async fn mark_accepted(
    db: &Db,
    id: Uuid,
    at: DateTime<Utc>,
) -> Result<u64, sqlx::Error> {
    let res = sqlx::query(
        r#"
        UPDATE invites
        SET accepted_at = $2
        WHERE id = $1
          AND accepted_at IS NULL
        "#,
    )
    .bind(id)
    .bind(at)
    .execute(db)
    .await?;
    Ok(res.rows_affected())
}

/// Revoke a pending invite. Tenant-scoped: the invite must belong to
/// `brand_id`. Accepted invites are not deletable through this path —
/// they remain as historical records.
#[instrument(skip(db), err)]
pub async fn delete_pending(
    db: &Db,
    id: Uuid,
    brand_id: Uuid,
) -> Result<u64, sqlx::Error> {
    let res = sqlx::query(
        r#"
        DELETE FROM invites
        WHERE id = $1
          AND brand_id = $2
          AND accepted_at IS NULL
        "#,
    )
    .bind(id)
    .bind(brand_id)
    .execute(db)
    .await?;
    Ok(res.rows_affected())
}
